-- Active: 1715533077061@@20.172.0.16@8080@donation_management_system

CREATE TABLE Workers (
    WID INT AUTO_INCREMENT,
    username VARCHAR(25),
    workerPassword VARCHAR(50),
    email VARCHAR(50),
    fullName VARCHAR(50),
    workerStatus VARCHAR(25),
    workerLocation VARCHAR(100),
    hoursWorked INT,
    startDate DATETIME,
    endDate DATETIME,
    CONSTRAINT WorkerPK PRIMARY KEY (WID)
);

CREATE TABLE Admins (
    AID INT NOT NULL,
    CONSTRAINT AdminPK PRIMARY KEY (AID),
    CONSTRAINT AdminFK FOREIGN KEY (AID) REFERENCES Workers(WID) ON DELETE CASCADE
);

CREATE TABLE Employees (
    EID INT NOT NULL,
    CONSTRAINT EmployeePK PRIMARY KEY (EID),
    CONSTRAINT EmployeeFK FOREIGN KEY (EID) REFERENCES Workers(WID) ON DELETE CASCADE
);

CREATE TABLE Volunteers (
    VID INT NOT NULL,
    CONSTRAINT VolunteerPK PRIMARY KEY (VID),
    CONSTRAINT VolunteerFK FOREIGN KEY (VID) REFERENCES Workers(WID) ON DELETE CASCADE
);

CREATE TABLE ExtraPermissions (
    EPID INT AUTO_INCREMENT,
    WID INT NOT NULL,
    CONSTRAINT ExtraPermissionPK PRIMARY KEY (EPID),
    CONSTRAINT ExtraPermissionPK FOREIGN KEY (WID) REFERENCES Workers(WID) ON DELETE CASCADE
);

CREATE TABLE VolunteerSkills (
    VSID INT AUTO_INCREMENT,
    VID INT NOT NULL,
    CONSTRAINT VolunteerSkillPK PRIMARY KEY (VSID),
    CONSTRAINT VolunteerSkillFK FOREIGN KEY (VID) REFERENCES Volunteers(VID) ON DELETE CASCADE
);

CREATE TABLE Messages (
    MeID INT AUTO_INCREMENT,
    receiver INT NOT NULL,
    sender INT,
    title VARCHAR(50),
    senderMessage VARCHAR(4000),
    CONSTRAINT MessagePK PRIMARY KEY (MeID),
    CONSTRAINT MessageReceiverFK FOREIGN KEY (receiver) REFERENCES Workers(WID) ON DELETE CASCADE,
    CONSTRAINT MessageSenderFK FOREIGN KEY (sender) REFERENCES Workers(WID) ON DELETE SET NULL
);

CREATE TABLE ActionNeeded (
    ANID INT AUTO_INCREMENT,
    receiver INT NOT NULL,
    AID INT,
    title VARCHAR(50),
    actionMessage VARCHAR(4000),
    CONSTRAINT ActionNeededPK PRIMARY KEY (ANID),
    CONSTRAINT ActionNeededWorkerFK FOREIGN KEY (receiver) REFERENCES Workers(WID) ON DELETE CASCADE,
    CONSTRAINT ActionNeededAdminFK FOREIGN KEY (AID) REFERENCES Admins(AID) ON DELETE SET NULL
);

CREATE TABLE addresses (
    EAID INT AUTO_INCREMENT,
    street VARCHAR(255),
    city VARCHAR(100),
    StateProvince  VARCHAR(100),
    postalCode VARCHAR(20),
    country VARCHAR(100),
    CONSTRAINT addressPK PRIMARY KEY (EAID)
);

CREATE TABLE PlannedEvents (
    EID INT AUTO_INCREMENT,
    rSVP INT,
    eventName VARCHAR(50),
    eventDescription VARCHAR(4000),
    eventDate DATETIME,
    EAID INT,
    CONSTRAINT PlannedEventPK PRIMARY KEY (EID),
    CONSTRAINT PlannedEventAddress FOREIGN KEY (EAID) REFERENCES addresses(EAID) ON DELETE SET NULL
);

CREATE TABLE WorkersAttending (
    WID INT NOT NULL,
    EID INT NOT NULL,
    CONSTRAINT WorkersAttendingPK PRIMARY KEY (WID, EID),
    CONSTRAINT WorkersAttendingFK1 FOREIGN KEY (WID) REFERENCES Workers(WID) ON DELETE CASCADE,
    CONSTRAINT WorkersAttendingFK2 FOREIGN KEY (EID) REFERENCES PlannedEvents(EID) ON DELETE CASCADE
);

CREATE TABLE inventoryLocations (
    LID INT AUTO_INCREMENT,
    locationName VARCHAR(100),
    capacity INT,
    cold BOOL,
    frozen BOOL,
    EAID INT,
    CONSTRAINT inventoryLocationPK PRIMARY KEY (LID),
    CONSTRAINT inventoryAddressFK FOREIGN KEY (EAID) REFERENCES addresses(EAID) ON DELETE RESTRICT
);

CREATE TABLE Inventory (
    IID INT AUTO_INCREMENT,
    itemName VARCHAR(50),
    itemDescription VARCHAR(200),
    quantity INT NOT NULL,
    unitOfMeasurement VARCHAR(25),
    unitCost DECIMAL(10,2),
    dateReceived DATETIME,
    itemCondition VARCHAR(25),
    Barcode VARCHAR(100),
    storageType VARCHAR(25),
    EID INT,
    LID INT,
    CONSTRAINT InventoryPK PRIMARY KEY (IID),
    CONSTRAINT InventoryFKEvent FOREIGN KEY (EID) REFERENCES PlannedEvents(EID) ON DELETE SET NULL, 
    CONSTRAINT InventoryFKLocation FOREIGN KEY (LID) REFERENCES inventoryLocations(LID) ON DELETE SET NULL
);

CREATE TABLE Nonedibles (
    NID INT NOT NULL,
    CONSTRAINT NonediblePK PRIMARY KEY (NID),
    CONSTRAINT NonedibleFK FOREIGN KEY (NID) REFERENCES Inventory(IID) ON DELETE CASCADE
);

CREATE TABLE Edibles (
    EID INT NOT NULL,
    perishable BOOL,
    CONSTRAINT EdiblePK PRIMARY KEY (EID),
    CONSTRAINT EdibleFK FOREIGN KEY (EID) REFERENCES Inventory(IID) ON DELETE CASCADE
);

CREATE TABLE Animals (
    AID INT NOT NULL,
    edible BOOL,
    perishable BOOL,
    CONSTRAINT AnimalPK PRIMARY KEY (AID),
    CONSTRAINT AnimalFK FOREIGN KEY (AID) REFERENCES Inventory(IID) ON DELETE CASCADE
);

CREATE TABLE Donors (
    DID INT AUTO_INCREMENT,
    fullName VARCHAR(100),
    EAID INT,
    CONSTRAINT DonorPK PRIMARY KEY (DID),
    CONSTRAINT DonarAddress FOREIGN KEY (EAID) REFERENCES addresses(EAID) ON DELETE SET NULL
);

CREATE TABLE Drecipts (
    DID INT NOT NULL,
    IID INT NOT NULL,
    DonationDate DATETIME,
    CONSTRAINT DreciptPK PRIMARY KEY (DID, IID),
    CONSTRAINT DreciptFK1 FOREIGN KEY (DID) REFERENCES Donors(DID) ON DELETE RESTRICT,
    CONSTRAINT DreciptFK2 FOREIGN KEY (IID) REFERENCES Inventory(IID) ON DELETE CASCADE
);

CREATE TABLE Transactions (
    TID INT AUTO_INCREMENT,
    DID INT NOT NULL,
    amount DECIMAL(10, 2),
    transactionStatus VARCHAR(50),
    CONSTRAINT TransactionPK PRIMARY KEY (TID),
    CONSTRAINT TransactionFK FOREIGN KEY (DID) REFERENCES Donors(DID) ON DELETE RESTRICT 
);

CREATE TABLE MonetaryDonations (
    MDID INT AUTO_INCREMENT,
    amount DECIMAL(10, 2),
    TID INT,
    CONSTRAINT DonationPK PRIMARY KEY (MDID),
    CONSTRAINT DonationFK FOREIGN  KEY (TID) REFERENCES Transactions(TID) ON DELETE RESTRICT
);

CREATE TABLE Recipients (
    RID INT AUTO_INCREMENT,
    fullName VARCHAR(50),
    EAID INT NOT NULL,
    CONSTRAINT RecipientPK PRIMARY KEY (RID),
    CONSTRAINT RecipientFK FOREIGN KEY (EAID) REFERENCES addresses(EAID) ON DELETE RESTRICT
);

CREATE TABLE MonetaryDistributionReceipts (
    MDRID INT AUTO_INCREMENT,
    RID INT NOT NULL,
    totalAmount DECIMAL(10, 2),
    distributionDate DATETIME,
    CONSTRAINT MonetaryDistributionReceiptPK PRIMARY KEY (MDRID),
    CONSTRAINT MonetaryDistributionReceiptFK FOREIGN KEY (RID) REFERENCES Recipients(RID) ON DELETE RESTRICT
);

CREATE TABLE MonetaryDistributions (
    MoDiID INT AUTO_INCREMENT,
    amount DECIMAL(10, 2),
    transactionStatus VARCHAR(50),
    MDID INT,
    RID INT,
    MDRID INT,
    CONSTRAINT MonetaryDistributionPK PRIMARY KEY (MoDiID),
    CONSTRAINT MonetaryDistributionDonation FOREIGN KEY (MDID) REFERENCES MonetaryDonations(MDID) ON DELETE RESTRICT,
    CONSTRAINT MonetaryDistributionReceipt FOREIGN KEY (MDRID) REFERENCES MonetaryDistributionReceipts(MDRID) ON DELETE RESTRICT
);

CREATE TABLE PhysicalReceipt (
    RID INT NOT NULL,
    IID INT NOT NULL,
    recievedDate DATETIME,
    CONSTRAINT PhysicalReceiptPK PRIMARY KEY (RID, IID),
    CONSTRAINT PhysicalReceiptFK1 FOREIGN KEY (RID) REFERENCES Recipients(RID) ON DELETE CASCADE,
    CONSTRAINT PhysicalReceiptFK2 FOREIGN KEY (IID) REFERENCES Inventory(IID) ON DELETE CASCADE
);

CREATE TABLE Request (
    RQID INT AUTO_INCREMENT,
    RID INT NOT NULL,
    AID INT,
    amount DECIMAL(10, 2),
    requestDate DATETIME,
    requestStatus VARCHAR(25),
    CONSTRAINT RequestPK PRIMARY KEY (RQID),
    CONSTRAINT RequestRecipient FOREIGN KEY (RID) REFERENCES Recipients(RID) ON DELETE CASCADE,
    CONSTRAINT RequestAdmin FOREIGN KEY (AID) REFERENCES Admins(AID) ON DELETE SET NULL
);

CREATE TABLE PhoneNumbers (
    PNID INT AUTO_INCREMENT,
    contactName VARCHAR(100),
    PhoneNumber VARCHAR(20),
    LID INT,
    DID INT,
    RID INT,
    CONSTRAINT PhoneNumbersPK PRIMARY KEY (PNID),
    CONSTRAINT PhoneNumbersFK1 FOREIGN KEY (LID) REFERENCES inventoryLocations(LID) ON DELETE SET NULL,
    CONSTRAINT PhoneNumbersFK2 FOREIGN KEY (DID) REFERENCES Donors(DID) ON DELETE CASCADE,
    CONSTRAINT PhoneNumbersFK3 FOREIGN KEY (RID) REFERENCES Recipients(RID) ON DELETE CASCADE
);

